name: Generate C2A Core Reference

on:
  workflow_dispatch:

jobs:
  generate_c2a_core_reference:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: pages

      - name: install deps
        run: |
          sudo apt install -y doxygen graphviz

      - name: clone c2a
        shell: bash
        run: |
          mkdir temp && cd $_
          mkdir clone
          git clone --depth 1 https://github.com/ut-issl/c2a-core.git ./clone/c2a-core
          cp -r ./clone/c2a-core/ ./c2a-core/
          cp -r ./clone/c2a-core/ ./c2a-core/Examples/minimum_user_for_s2e/src/src_core/
          cd ./c2a-core/Examples/minimum_user_for_s2e/src/src_core/
          rm -rf ./Examples
          rm -rf ./Docs

      - name: clearn previous html
        working-directory: ./docs
        run: |
          rm -rf ./c2a-core
          mkdir ./c2a-core

      - name: build
        working-directory: ./temp/c2a-core/Examples/minimum_user_for_s2e
        run: doxygen

      - name: move files
        working-directory: ./docs/c2a-core/html
        run: mv * ../

      - name: deploy
        run: |
          git branch -a
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          # 1 file changed, 2 insertions(+), 3 deletions(-) みたいなのをひっかける
          if (git diff --shortstat | grep '[0-9]'); then \
            git commit -am "update doxygen: C2A Core";  \
            git push origin;  \
          fi
